### PR TITLE
Global naming for tag constants

### PR DESCRIPTION
**Pull request by AnaMontes11**
https://jira.tid.es/browse/DSNCORE-1285

**Merge blocked until all platforms works on it**
- [x] Android — https://jira.tid.es/browse/ANDROID-10521
- [x] iOS — https://jira.tid.es/browse/IOS-7356
- [x] Web — https://jira.tid.es/browse/WEB-508

This changes trigger changes in components (tags & chips)

### CODE REVIEW

**Comment by yceballost** [comment]
En blau no cambiamos el `neutralLow` a `grey1`?

https://github.com/Telefonica/mistica-design/pull/456/files#diff-e1fb21d26efb3ee710f71b0b5d854b78766f61c8cc802c500bd7cf7fc95e9d05R88

**Comment by AnaMontes11** [comment]
> En blau no cambiamos el `neutralLow` a `grey1`?
> 
> https://github.com/Telefonica/mistica-design/pull/456/files#diff-e1fb21d26efb3ee710f71b0b5d854b78766f61c8cc802c500bd7cf7fc95e9d05R88

No lo he cambiado porque en Blau el Grey 2 es el equivalente al Grey 1 de otras marcas

**Comment by yceballost** [comment]
> > En blau no cambiamos el `neutralLow` a `grey1`?
> > [#456 (files)](https://github.com/Telefonica/mistica-design/pull/456/files#diff-e1fb21d26efb3ee710f71b0b5d854b78766f61c8cc802c500bd7cf7fc95e9d05R88)
> 
> No lo he cambiado porque en Blau el Grey 2 es el equivalente al Grey 1 de otras marcas

perfecto, solo por hacer ✅

**Review by yceballost — APPROVED** [review]
nice 🤩

**Pull request merged**
