### PR TITLE
update hover/pressed tokens

### PR DESCRIPTION
**Pull request by andredelramo-hm**
Update the tokens backgroundContainerHover to 0.05 and backgroundContainerPressed to 0.08. Additionally, the Blau token will use blauBlueSecondary from its palette, and Telefonia will use telefonicaBlue70.

### CODE REVIEW

**Review by yceballost — APPROVED** [review]

**Comment by aweell** [comment]
Tokens preview: 
* `backgroundContainerHover`: https://mistica-design.vercel.app/tokens-map/aramo-tokens-hover-pressed/blau/color/backgroundContainerHover/
* `backgroundContainerPressed`: https://mistica-design.vercel.app/tokens-map/aramo-tokens-hover-pressed/blau/color/backgroundContainerPressed/

**Review by aweell — COMMENTED** [review]
What happens with `backgroundContainerBrandHover` and `backgroundContainerBrandPressed` in the brands that have also the values of 0.03 and 0.05 in dark? wouldn't be weird to have different values

Screenshot 2024-11-28 at 20 21 34

**Comment by aweell** [comment]
Web preview: https://mistica-web-jpho-jersvb39o-alex-buenos-projects.vercel.app/?vercelToolbarCode=VufRUgo-OpNZTth

**Comment by andredelramo-hm** [comment]
@aweell I understand your point, but I'm not sure if it should be considered another issue. I would need to see where tokens are being used and understand why there are differences between dark and light modes.

https://www.figma.com/design/nBIZk0SZEeL9g6f5KnJwNF/Test-hover-and-pressed-tokens?node-id=0-1&t=D99wxkE7dSM5vCX1-1

**Comment by aweell** [comment]
> @aweell I understand your point, but I'm not sure if it should be considered another issue. I would need to see where tokens are being used and understand why there are differences between dark and light modes.
> 
> https://www.figma.com/design/nBIZk0SZEeL9g6f5KnJwNF/Test-hover-and-pressed-tokens?node-id=0-1&t=D99wxkE7dSM5vCX1-1

https://www.figma.com/design/vCUyyZapiXKAe6TFJmvQyw?node-id=2071-1948#1033275331

These tokens where meant to be used for overlays that are on top of containers with brand colors (for example a poster or display data inverse card) since the amount of black needed to show a change over brand vs over white is not the same.

For the sake of consistency i would use these tokens in the `Action/navigation + active` variant as suggested. In that case at least we would need to change those to the same values the "non brand" tokens now will have in dark.

**Review by aweell — APPROVED** [review]

**Pull request merged**
